import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Banner from '/components/Banner'
import Navbar from '/components/Navbar'
import Footer from '/components/contact'
import utilStyles from '../styles/articles.module.css'
import { getSortedPostsData } from '../lib/posts'
import Date from '../components/date'


export async function getStaticProps() {
  const allPostsData = getSortedPostsData()

  return {
    props: {
      allPostsData
    }
  }
}

export default function Home({ allPostsData }) {
  return (
    <>

      <Head>
        <title>Entre Mates Te Conté</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
        <Navbar home></Navbar>
      </header>
      <Banner></Banner>
      <div className="container">
        <main className={styles.main}>
          <br></br>
          <section className="articles">
            <h2 id="art-ent">Artículos y entrevistas</h2><br />
            <ul>
              {allPostsData.map(({ id, date, title, image, description }) => (
                <li key={id}>
                  <div className="row">
                    <Link href={`/posts/${id}`}>
                      <a className="zoom">

                        <div className="row g-0">
                          <div className="col-md-3">
                            <Image src={image} alt="Article cover" height={192} width={315} />
                          </div>
                          <div className="col-md-9">
                            <h2>{title}</h2>
                            <small className={utilStyles.lightText}>
                              <Date dateString={date} />
                            </small>
                            <br /><br />
                            <p>{description}</p>
                          </div>
                        </div>

                      </a>
                    </Link>
                    <br />

                  </div>
                </li>
              ))}
            </ul>
          </section>
          <br />
        </main>
      </div>
      <footer id="footer">
        <Footer></Footer>
      </footer>
    </>

  )
}
